### ISSUE TITLE
Reporte de app

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-equipo-magaly#1]
[reporte de app_desarrollo de realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-equipo-magaly/files/14313490/reporte.de.app_desarrollo.de.realidad.aumentada.pdf)

**Comment by josealfredo79** [comment]
Calificacion....???

**Comment by IrvingFernand0** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
